import type { Reaction } from "./types";

interface ReactionSet {
  label: string;
  reactions: Reaction[];
}

export const reactionSets: Record<string, ReactionSet> = {
  default: {
    label: "Default",
    reactions: [
      {
        id: "0",
        speed: "1",
        enabled: "true",
        title: "Like",
        icon: "heart",
        primaryColor: "#eb34b1",
        secondaryColor: "",
        style: "fas",
        effect: "physics-floatUp",
        directional: false,
        type: "fontawesome",
        path: "",
        maxWidth: 200,
        maxHeight: 200,
        fontSize: 48,
      },
      {
        id: "1",
        speed: "1",
        enabled: "true",
        title: "OMG",
        icon: "triangle-exclamation",
        primaryColor: "#c52525",
        secondaryColor: "#efaa4b",
        style: "fa-duotone",
        effect: "physics-floatUp",
        directional: false,
        type: "fontawesome",
        path: "",
        maxWidth: 200,
        maxHeight: 200,
        fontSize: 48,
      },
      {
        id: "2",
        speed: "1",
        enabled: "true",
        title: "Axe",
        icon: "axe",
        primaryColor: "#5f7e96",
        secondaryColor: "#c1c1c1",
        style: "fa-duotone",
        effect: "physics-toss",
        directional: true,
        type: "fontawesome",
        path: "",
        maxWidth: 200,
        maxHeight: 200,
        fontSize: 48,
      },
      {
        id: "3",
        speed: "1",
        enabled: "true",
        title: "droplet",
        icon: "droplet",
        primaryColor: "#a4fbf7",
        secondaryColor: "#00a6ff",
        style: "fa-duotone",
        effect: "physics-drop",
        directional: false,
        type: "fontawesome",
        path: "",
        maxWidth: 200,
        maxHeight: 200,
        fontSize: 48,
      },
      {
        id: "4",
        speed: "1",
        enabled: "true",
        title: "fire",
        icon: "fire",
        primaryColor: "#dd0000",
        secondaryColor: "#f5c767",
        style: "fa-duotone",
        effect: "physics-floatUp",
        directional: false,
        type: "fontawesome",
        path: "",
        maxWidth: 200,
        maxHeight: 200,
        fontSize: 48,
      },
      {
        id: "5",
        speed: "1",
        enabled: "true",
        title: "x",
        icon: "times",
        primaryColor: "#dd0000",
        secondaryColor: "rgba(255,255,255,0.6)",
        style: "fas",
        effect: "shutdown",
        directional: false,
        type: "fontawesome",
        path: "",
        maxWidth: 200,
        maxHeight: 200,
        fontSize: 48,
      },
    ],
  },
  sciFantasy: {
    label: "Sci-Fantasy",
    reactions: [
      {
        id: "0",
        speed: "1",
        enabled: "true",
        title: "Like",
        icon: "heart",
        primaryColor: "#eb34b1",
        secondaryColor: "",
        style: "fas",
        effect: "physics-floatUp",
        directional: false,
        type: "fontawesome",
        path: "",
        maxWidth: 200,
        maxHeight: 200,
        fontSize: 48,
      },
      {
        id: "1",
        speed: "1",
        enabled: "true",
        title: "Warning",
        icon: "siren",
        primaryColor: "#5b7b8e",
        secondaryColor: "#e60404",
        style: "fa-duotone",
        effect: "physics-floatUp",
        directional: false,
        type: "fontawesome",
        path: "",
        maxWidth: 200,
        maxHeight: 200,
        fontSize: 48,
      },
      {
        id: "2",
        speed: "1",
        enabled: "true",
        title: "Laser Sword",
        icon: "sword-laser",
        primaryColor: "#7a7a7a",
        secondaryColor: "#51e367",
        style: "fa-duotone",
        effect: "physics-toss",
        directional: true,
        type: "fontawesome",
        path: "",
        maxWidth: 200,
        maxHeight: 200,
        fontSize: 48,
      },
      {
        id: "3",
        speed: "1",
        enabled: "true",
        title: "Space Station",
        icon: "space-station-moon-construction",
        primaryColor: "#cfcfcf",
        secondaryColor: "#585858",
        style: "fa-duotone",
        effect: "physics-drop",
        directional: false,
        type: "fontawesome",
        path: "",
        maxWidth: 200,
        maxHeight: 200,
        fontSize: 48,
      },
      {
        id: "4",
        speed: "1",
        enabled: "true",
        title: "Ship",
        icon: "starship-freighter",
        primaryColor: "#5f6d7e",
        secondaryColor: "#aeaeae",
        style: "fa-duotone",
        effect: "physics-toss",
        directional: false,
        type: "fontawesome",
        path: "",
        maxWidth: 200,
        maxHeight: 200,
        fontSize: 48,
      },
      {
        id: "5",
        speed: "1",
        enabled: "true",
        title: "x",
        icon: "square-xmark",
        primaryColor: "#dd0000",
        secondaryColor: "rgba(255,255,255,0.6)",
        style: "fas",
        effect: "shutdown",
        directional: false,
        type: "fontawesome",
        path: "",
        maxWidth: 200,
        maxHeight: 200,
        fontSize: 48,
      },
    ],
  },
  cozy: {
    label: "Cozy",
    reactions: [
      {
        id: "0",
        speed: "1",
        enabled: "true",
        title: "Like",
        icon: "leaf",
        primaryColor: "#a8df35",
        secondaryColor: "#6c9733",
        style: "fa-duotone",
        effect: "physics-flutterDown",
        directional: false,
        type: "fontawesome",
        path: "",
        maxWidth: 200,
        maxHeight: 200,
        fontSize: 48,
      },
      {
        id: "1",
        speed: "1",
        enabled: "true",
        title: "OMG",
        icon: "triangle-exclamation",
        primaryColor: "#f5ad42",
        secondaryColor: "",
        style: "fas",
        effect: "physics-floatUp",
        directional: false,
        type: "fontawesome",
        path: "",
        maxWidth: 200,
        maxHeight: 200,
        fontSize: 48,
      },
      {
        id: "2",
        speed: "1",
        enabled: "true",
        title: "Axe",
        icon: "mug-tea",
        primaryColor: "#87b83d",
        secondaryColor: "#ddbeaa",
        style: "fa-duotone",
        effect: "physics-floatUp",
        directional: true,
        type: "fontawesome",
        path: "",
        maxWidth: 200,
        maxHeight: 200,
        fontSize: 48,
      },
      {
        id: "3",
        speed: "1",
        enabled: "true",
        title: "droplet",
        icon: "droplet",
        primaryColor: "#a4fbf7",
        secondaryColor: "#6bc7fe",
        style: "fa-duotone",
        effect: "physics-drop",
        directional: false,
        type: "fontawesome",
        path: "",
        maxWidth: 200,
        maxHeight: 200,
        fontSize: 48,
      },
      {
        id: "4",
        speed: "1",
        enabled: "true",
        title: "fire",
        icon: "candle-holder",
        primaryColor: "#f5efc5",
        secondaryColor: "#eb8c34",
        style: "fa-duotone",
        effect: "physics-floatUp",
        directional: false,
        type: "fontawesome",
        path: "",
        maxWidth: 200,
        maxHeight: 200,
        fontSize: 48,
      },
      {
        id: "5",
        speed: "1",
        enabled: "true",
        title: "x",
        icon: "times",
        primaryColor: "#dd0000",
        secondaryColor: "rgba(255,255,255,0.6)",
        style: "fas",
        effect: "shutdown",
        directional: false,
        type: "fontawesome",
        path: "",
        maxWidth: 200,
        maxHeight: 200,
        fontSize: 48,
      },
    ],
  },
  tavern: {
    label: "Tavern",
    reactions: [
      {
        id: "0",
        speed: "1",
        enabled: "true",
        title: "Like",
        icon: "heart",
        primaryColor: "#eb34b1",
        secondaryColor: "",
        style: "fas",
        effect: "physics-floatUp",
        directional: false,
        type: "fontawesome",
        path: "",
        maxWidth: 200,
        maxHeight: 200,
        fontSize: 48,
      },
      {
        id: "1",
        speed: "1",
        enabled: "true",
        title: "OMG",
        icon: "triangle-exclamation",
        primaryColor: "#c52525",
        secondaryColor: "#efaa4b",
        style: "fa-duotone",
        effect: "physics-floatUp",
        directional: false,
        type: "fontawesome",
        path: "",
        maxWidth: 200,
        maxHeight: 200,
        fontSize: 48,
      },
      {
        id: "2",
        speed: "1",
        enabled: "true",
        title: "Axe",
        icon: "axe",
        primaryColor: "#5f7e96",
        secondaryColor: "#c1c1c1",
        style: "fa-duotone",
        effect: "physics-toss",
        directional: true,
        type: "fontawesome",
        path: "",
        maxWidth: 200,
        maxHeight: 200,
        fontSize: 48,
      },
      {
        id: "3",
        speed: "1",
        enabled: "true",
        title: "Beer",
        icon: "beer-mug",
        primaryColor: "#fee2a0",
        secondaryColor: "#69432c",
        style: "fa-duotone",
        effect: "physics-toss",
        directional: false,
        type: "fontawesome",
        path: "",
        maxWidth: 200,
        maxHeight: 200,
        fontSize: 48,
      },
      {
        id: "4",
        speed: "1",
        enabled: "true",
        title: "Meat",
        icon: "meat",
        primaryColor: "#ae4020",
        secondaryColor: "#fbe7bd",
        style: "fa-duotone",
        effect: "physics-floatUp",
        directional: false,
        type: "fontawesome",
        path: "",
        maxWidth: 200,
        maxHeight: 200,
        fontSize: 48,
      },
      {
        id: "5",
        speed: "1",
        enabled: "true",
        title: "x",
        icon: "times",
        primaryColor: "#dd0000",
        secondaryColor: "rgba(255,255,255,0.6)",
        style: "fas",
        effect: "shutdown",
        directional: false,
        type: "fontawesome",
        path: "",
        maxWidth: 200,
        maxHeight: 200,
        fontSize: 48,
      },
    ],
  },
};
